### ISSUE TITLE
Better service name detection

### ISSUE THREAD

**Issue by Yamakaky** [chrisguidry/pytest-opentelemetry#12]
Currently the service name is taken from the directory name. The standard way is to use the env variable `OTEL_SERVICE_NAME`. That's what `Resource.create()` does by default. Maybe have a priority list like env variable > entry in `pyproject.toml` > directory name.

https://github.com/chrisguidry/pytest-opentelemetry/blob/main/src/pytest_opentelemetry/resource.py

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration

**Comment by chrisguidry** [comment]
Thanks @Yamakaky, it turns out that I wasn't also including OTEL's built-in resource detector which does this.  Great catch!

**Comment by chrisguidry** [comment]
I'm still on the lookout for a better way to pick up the current "project's" name, but I don't think there is a standard for this.  I'd recommend using `pytest-env` and its `--env` setting in your `pyproject.toml` to set `OTEL_RESOURCE_ATTRIBUTES`.

**Comment by Yamakaky** [comment]
Nice! Maybe add a comment in README to show that pytest-env is an option now?

**Comment by chrisguidry** [comment]
Great idea, I wrote a couple new sections, let me know what you think: 

https://github.com/chrisguidry/pytest-opentelemetry#installation-and-usage (look for the part talking about `pytest-env`)

https://github.com/chrisguidry/pytest-opentelemetry#why-instrument-my-test-suite (just a general overview, does this resonate with why you're using `pytest-opentelemetry`?)

**Comment by Yamakaky** [comment]
Nice! My usecase is a bit different: I have a grafana dashboard where I do the matching between traceIDs from tavern and from our app. This helps us in finding the root cause of a test failure.
