### ISSUE TITLE
Root span should be marked a failure if any test fails

### ISSUE THREAD

**Issue by chrisguidry** [chrisguidry/pytest-opentelemetry#14]
_Reported by @Yamakaky in #11, splitting out here to work on independently_

Currently when a single test fails, it's span is correctly considered a failure, but the overall test's span is still considered a success.  This doesn't match expectations, since when you have a single failed `pytest` test, your entire test suite is considered failed (`pytest` will return an exit code after running, etc.)

**Comment by Yamakaky** [comment]
Done
