### ISSUE TITLE
Please support TRACEPARENT env variable for passing the trace parent information

### ISSUE THREAD

**Issue by cazador481** [chrisguidry/pytest-opentelemetry#20]
The TRACEPARENT env variable is becoming a standard way to pass the traceparent information between processes.

**Comment by chrisguidry** [comment]
That makes a ton of sense!

**Comment by Yamakaky** [comment]
Looks good. From what I can see it's not standardized yet but used by multiple products, correct?

https://github.com/open-telemetry/opentelemetry-specification/issues/740

**Comment by cazador481** [comment]
That is correct.

**Comment by chrisguidry** [comment]
Thanks, folks!  The new release with this change is up: https://pypi.org/project/pytest-opentelemetry/  

`pytest-opentelemetry>=0.6.0`

**Comment by cazador481** [comment]
Thank you for the quick turn around
