### ISSUE TITLE
Collect spans for fixture setup and teardown

### ISSUE THREAD

**Issue by drcraig** [chrisguidry/pytest-opentelemetry#25]
Hey @chrisguidry! Long time, no see, hope you're doing well. This is a beautiful little tool :)

I had an idea that I'd be happy to help implement if you think you'd want to include it: collecting spans for fixture setup and teardown, in addition to the tests themselves. In my [usecase](https://www.youtube.com/watch?v=spCOYV4KyPA&ab_channel=PyConUS), we are testing hardware, and the setup and teardown can be quite time consuming, so we're eager to find which fixtures are taking the most time. Maybe these long running fixtures can be refactored to be faster, or maybe that can be bumped up to be module or session scoped.

To implement, I think I'd envision there being a span for the entire test case covering setup, test, and teardown, and then underneath that would be spans for for the fixture setups, the actual test case, and then the fixture teardowns.  Maybe that could be as simple as doing the same thing you have in pytest_runtest_protocol but for pytest_runtest_setup, pytest_runtest_call, and pytest_runtest_teardown? I'll see if I can experiment on that some time soon.

**Comment by chrisguidry** [comment]
That sounds great, I definitely hoped to get spans covering each test phase like that, please send it along whenever you have time.  Hope everything is going well!

**Comment by sihil** [comment]
I just happened across this repo when pondering how to get to the bottom of some slow test run times. In our case I can see that the fixtures are taking a considerable portion of the test run time. We run against a real DB and have many fixtures that wrangle the DB into the right state for a particular test. Being able to generate spans breaking everything down would be a revolution so I'd love for this data to be collected as described by @drcraig.

Nice project and nice beard @chrisguidry!

**Comment by chrisguidry** [comment]
@sihil that's _exactly_ the kind of situation I had in mind for `pytest-opentelemetry`!  I'm a big believer in unit tests using real databases, but test iteration speed becomes a big concern over time.  I'm going to give this a look this weekend, it should be pretty straightforward.

**Comment by chrisguidry** [comment]
I just cut a release 0.7.0 with this, give it a spin and let me know what you think!

**Comment by drcraig** [comment]
Nice! I'll give it a look at a try. I actually had some time on a couple of long flights this week to work on it, so was going to send you a pull request this weekend, but you beat me to it. Sorry, should have spoken up and saved some duplication of effort. I'll look through how you approached it and see if covers it all, or if there is anything worth salvaging from mine. I had to resort to some cleverness to try to capture individual fixture teardown times, so I'm interested to see if you found a cleaner way to do it.
