### ISSUE TITLE
access and modify dynamic spans during a test run

### ISSUE THREAD

**Issue by nammn** [chrisguidry/pytest-opentelemetry#30]
Thanks for the great project!
Is there a way to access the dynamically created span to add attributes? Or a way to pass attributes per test to the then created span?

**Comment by agardnerIT** [comment]
Similarly, I want to access the span ID / parent ID and then send a log (with that span ID) which my backend system can then use to correlate the log + span together.

Note: Generating and sending the log is (obviously) out of scope for pytest. All I need from pytest is the ability to get the span ID:

```
def test_do_something():
  # Something like...
  test_span_id = pytest.get_current_span_id()
  sendLog(span_id=test_span_id) # Custom method implemented by me
```

**Comment by nammn** [comment]
@chrisguidry indeed! That is working perfect. Thanks! I am closing this issue!
