### ISSUE TITLE
Correctly handles xdist uninstalled

### ISSUE THREAD

**Issue by Yamakaky** [chrisguidry/pytest-opentelemetry#9]
When running pytest-opentelemetry without xdist installed, I get this error:

`pluggy._manager.PluginValidationError: unknown hook 'pytest_configure_node' in plugin <pytest_opentelemetry.instrumentation.OpenTelemetryPlugin object at 0x7fda25c22fe0>`

I think this is similar to https://github.com/pytest-dev/pytest-randomly/pull/248/files which could be adapted.

**Comment by chrisguidry** [comment]
Thanks for the report, @Yamakaky!  I'll take a look this morning

**Comment by chrisguidry** [comment]
This was released in [version 0.4.0 to PyPI](https://pypi.org/project/pytest-opentelemetry/).

**Comment by Yamakaky** [comment]
Nice, I'll try that.
